Algoritmo "ex05A"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson
// Descrição   : Solicitar um valor e escrever o seu antecessor
// Autor(a)    : Caio Monte Santo Barbosa
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número e veja o seu antecessor:")
leia(valor)

escreva("O antecessor de ",valor," é:",(valor-1))

Fimalgoritmo